### ISSUE TITLE
A seller should be able to update an product item from their collection

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-fe#18]
**Description**

As a Seller, I should be able to update a specific item  in my collection so that the specs, quantities and prices are always up to date.

**Acceptance criteria**

- The seller should be presented with a form prefilled with the current values of the item's details.
- Editable fields should be clearly marked as editable.
- The seller should be presented with an interface to upload image(s) of the item and/or a short video clip of the same.
- A simple but intuitive form should clearly show the editable fields.
- Existing images should have a remove/update interface.
- The form may include additional optional fields such as an interface for file upload, an item description field, available stock quantity, etc.

**Dev notes:**

- The form should be designed with user experience in mind, ensuring simplicity and intuitiveness.
- Editable fields should be visually distinguishable, possibly using different colors, borders, or icons.
- Provide options to remove or update each image.
- Allow for multiple file uploads.
- Include a save button that updates the item details in the database upon submission.
- Ensure responsiveness for different device sizes, maintaining usability on mobile devices.

**Comment by GSinseswa721** [comment]
## Implementation plan
###  Deliverables at the end of the project.
A seller, will be able to update a specific item in the collection so that the specs, quantities and prices are always up to date.

## Tools
- Typescript.
- React Framework.
- Use Tailwind CSS.

## Schedule of implementation of the various parts

- Implement the API integration and UI designs; completion is scheduled for Thursday, June 21, 2024.
- Begin testing by Friday, June 21, 2024.
- The entire work will be finalized on Monday, June 24, 2024.
